name: Convert Rules

on:
  push:
    paths:
      - 'Surge/*.list'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Convert files
        run: |
          python Scripts/Surge2Egern.py --pattern "Surge/*.list" --skip-no-resolve-files '["Surge/China.list"]'
          python Scripts/Surge2Mihomo.py --pattern "Surge/*.list"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Egern/*.yaml Mihomo/*.yaml
          git commit -m "Github Action auto convert rules" || echo "No changes to commit"
          git push origin main
